apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jesuspb-cert
  namespace: default
spec:
  secretName: jesuspb-dev-tls
  dnsNames:
    - jesuspb.dev
    - portfolio.jesuspb.dev
    - crazyweekend570.jesuspb.dev
    - backend.jesuspb.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
